### ISSUE TITLE
Source Data: MGP Data by Gender still needed

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#10]

**Comment by benjaminrobinson** [comment]
I think I have this complete...Will just have to run by folks on our end!

**Comment by benjaminrobinson** [comment]
I have also added to the min-max file so that the MGPs have min-max values...this was inputted before.

**Comment by benjaminrobinson** [comment]
Awaiting Jeff's feedback on this before closing the issue...

**Comment by gwenrr** [comment]
OSSE is fine with this
