### ISSUE TITLE
Sped APR: 3c key changes

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#100]
In apr.json 3c elementary reading has they key:    "3c_elem-math", but in sped_apr it's           "3c_elem.math". This is causing these metrics not to show up and would require custom coding around. Ben, hoping this is a small fix? Thanks!

**Comment by benjaminrobinson** [comment]
Will be implemented/fixed in the next push!  Not sure why we never noticed that (probably because no one was doing the development on it yet and hadn't looked closely at the data) but it will be fixed in the next push for sure.

**Comment by mepps** [comment]
Thanks, Ben!
