### ISSUE TITLE
ReportCards has come in as a submodule

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#102]
Will work on finding a way to "un-submodule a git submodule"...Just wanted everyone to know!  Will this have a negative effect on the data import, @cmgiven or @mepps?

**Comment by benjaminrobinson** [comment]
Is this a good way to go about the situation?
http://stackoverflow.com/questions/1759587/un-submodule-a-git-submodule

**Comment by cmgiven** [comment]
I've never encountered submodules before. No real urgency here, as we can see the exports. And this code should eventually be replaced with something much more similar to the new ETL, rather than this old string concatenation approach.

**Comment by benjaminrobinson** [comment]
Agreed...

**Comment by benjaminrobinson** [comment]
Chris and I discovered why the ReportCards came in as a submodule and have come to the conclusion that its actually probably a good idea for the ReportCards to stay that way (as a submodule) and then they can go away once the creation of the rest of the individual JSONs has occurred on OSSE's end.  This list of files includes:
- pcsb_pmf (done!)
- overview (done!)
- program_info
- special_ed
- amo_targets
