### ISSUE TITLE
Can't parse overview.json file

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#103]
Hi Ben, I'm getting an error with the overview.json files that they can't be parsed. However, when looking at the files, I don't see anything wrong. Do you know why this could be happening? Also, should they be imported with this push?

**Comment by benjaminrobinson** [comment]
I would consult @cmgiven  but I don't think they are is a necessity that the overview files be imported with this push...However, that is strange that they can't be parsed.  The files do look like they are standard json so that is definitely weird.  I'll come back to this tomorrow morning.

This file from the LearnDC repo:  https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/school/0101/overview.json

and this is from the Social Driver repo:  https://github.com/socialdriver/learndc-data/blob/master/converted/school/0101/overview.json

for example.

**Comment by cmgiven** [comment]
It can't parse because the 2014 PMF key object is missing the "category." See below.

``` json
"pmf": {
  "id": "pcsb_pmf",
  "data": [
    {
      "key": {
        "year": "2013",
        "category": "HS"
      },
      "val": {
        "score": 0.136,
        "tier": null,
        "url": "dashboard.dcpcsb.org/detailed/83"
      }
    },
    {
      "key": {
        "year": "2014"
      },
      "val": {
        "score": 0.137,
        "tier": null,
        "url": "dashboard.dcpcsb.org/detailed/83"
      }
    }
  ]
}
```

**Comment by cmgiven** [comment]
Also, not a necessity that they be imported with this push, although if its a quick fix tomorrow, that would be ideal.

**Comment by benjaminrobinson** [comment]
The new PMF data from PCSB for 13-14 tiers did not come with a category designation so that would just be a missing value all the way through...Should I just add a column to the table to make the tables match and re-create the overview files that way?

**Comment by cmgiven** [comment]
Yeah; we're not currently doing anything with it, but it is intended to support the ability to have two PMFs for a single school. If it was present, a null value would probably suffice.

**Comment by benjaminrobinson** [comment]
I see...I can make the change and commit and push the files now if you'd like!

**Comment by benjaminrobinson** [comment]
Changes have been committed to the site...

**Comment by benjaminrobinson** [comment]
@mepps:  can you please update me when you can on whether the newly committed/pushed overview json files have been imported and are parseable!  Thanks!

**Comment by cmgiven** [comment]
Unfortunately, Maggie just let me know that the files again refused to parse. @mepps: do you have an suggestions as to where to look to diagnose what is causing the problem? As far as I can tell, the format matches, and the files are valid JSON.

**Comment by mepps** [comment]
I printed the error message and it's:

undefined method `[]' for nil:NilClass


I'm investigating where that's coming from, but maybe the empty array in data?

		"data": [

		]

**Comment by mepps** [comment]
Still testing and I'm not sure that's it

**Comment by mepps** [comment]
It looks the error is coming from somewhere it's trying to read the file--still looking.

**Comment by mepps** [comment]
I think it just has to do with the structure being slightly different. the error was coming from the script where we downcase all subgroup names which we wouldn't want to do with this data anyways. I'll just have to add an exception for overview.json.
