### ISSUE TITLE
DC Report Card CAS Subgroup Keys Showing?

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#104]
Something's rotten in the State Report Card...(Hamlet reference ftw) but in all seriousness...this probably shouldn't be showing!

![image](https://cloud.githubusercontent.com/assets/7928978/6064232/9c4740d2-ad2a-11e4-9bb3-912a30e45f59.png)

**Comment by mepps** [comment]
Ben, where are you seeing this? Here's what I see on the DC State report card. (Also I'm at home sick today, so may not be as responsive.)
![screen shot 2015-02-05 at 12 58 15 pm](https://cloud.githubusercontent.com/assets/4406809/6065877/b2f7bdfa-ad36-11e4-9f3d-7af053393c06.png)

**Comment by cmgiven** [comment]
Change "Compare" to "Subgroups".

Hope you feel better!

**Comment by benjaminrobinson** [comment]
Exactly what Chris, said...Feel better soon, Maggie!

**Comment by gwenrr** [comment]
It seems this is only in proficiency (not in participation or performance levels).

**Comment by mepps** [comment]
![screen shot 2015-02-09 at 9 00 22 am](https://cloud.githubusercontent.com/assets/4406809/6107587/23391bf8-b03a-11e4-9a9c-156ba6959398.png)

Fixed on prod.
