### ISSUE TITLE
PCSB Tiers and URLs need to be updated

### ISSUE THREAD

**Issue by cmgiven** [DC-OSSE/LearnDC_v2#105]
It appears to be a valid link, but the javascript click event callback is preventing it from taking the user to the destination.

This is on the report card of any charter school, for example: http://www.learndc.org/schoolprofiles/view?s=1100#reportcard

**Comment by mepps** [comment]
I'm looking into this. This error appears in the console:  Uncaught TypeError: Cannot read property 'top' of undefined app.js:228

**Comment by cmgiven** [comment]
Yes, because it's not an anchor link. Needs to go off page.

**Comment by mepps** [comment]
I got this working locally but the link for school 1100 goes to http://www.dcpcsb.org/SchoolProfile.aspx?sid=21 and that returns a Page not found error. Any thoughts?

**Comment by cmgiven** [comment]
Great. Let's push the fix so that the bug is closed on our end. The URLs are defined in the data files, so @benjaminrobinson, flagging for you.

**Comment by mepps** [comment]
I've deployed the change to prod, but are we sure that's where the link should go? I tested another school and it also got a page not found error.

**Comment by cmgiven** [comment]
PCSB redid their site recently, and clearly didn't redirect old links. They will be updated once Ben can recreate the exhibit with the new ETL.

**Comment by mepps** [comment]
Thanks Chris!

**Comment by cmgiven** [comment]
Thanks, Maggie. I'm not seeing the fix after clearing my cache. Possibly related to Acquia transition?

**Comment by mepps** [comment]
Hmm, I'm on the live site and the links are working. I just cleared an additional cache though so see if if works for you now.

**Comment by cmgiven** [comment]
That did the trick.

**Comment by mepps** [comment]
Great!

**Comment by benjaminrobinson** [comment]
I think I know what's happening with the old links...So the links from previous PMF Tier data sites have all been consolidated on PCSB's end (i.e. one can view PMF data from 2012 or earlier using the same site to view the new data.).  These new URLs can be found in the overview files that I pushed.  Does that make sense at all?

**Comment by cmgiven** [comment]
Yes. But in addition to the overview files, we need updated pcsb_pmf report card exhibits. These are what power the dashboard icon.

**Comment by benjaminrobinson** [comment]
Hmm...the overview files should include new PMF tier and score data.  Here's an example!
https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/school/0153/overview.json

**Comment by cmgiven** [comment]
Yes, we see them there. However, the report card doesn't know about the overview files. It's looking for the presence of a pcsb_pmf exhibit, which has yet to be updated.

**Comment by cmgiven** [comment]
Example: https://github.com/socialdriver/learndc-data/blob/master/converted/school/0101/pcsb_pmf.json

**Comment by benjaminrobinson** [comment]
I see...will try to get on that.

**Comment by benjaminrobinson** [comment]
The pcsb_pmf.json files will be uploaded to the repository at the time of the next data push/commit!
