### ISSUE TITLE
ER - wrong year labels; SC = 1110 and 0218

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#107]
For SC = 1110
![screenshot 2015-02-13 11 46 16](https://cloud.githubusercontent.com/assets/7264714/6191343/a84b6320-b376-11e4-9128-16cf588c2ee9.png)

**Comment by mepps** [comment]
![screen shot 2015-02-13 at 2 32 03 pm](https://cloud.githubusercontent.com/assets/4406809/6193843/1d315c56-b38d-11e4-891b-81aa85305278.png)
Fixed on prod.
