### ISSUE TITLE
ER - percent labels missing SC = 0196

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#108]
![screenshot 2015-02-13 11 49 13](https://cloud.githubusercontent.com/assets/7264714/6191366/d77cdcfa-b376-11e4-8eb9-57fbd312c450.png)

**Comment by mepps** [comment]
Looks like a range issue. I'm looking into it, but it's a little more complicated than past range issues.

**Comment by benjaminrobinson** [comment]
Also, this doesn't look good!
![image](https://cloud.githubusercontent.com/assets/7928978/6194092/f613b22a-b38e-11e4-8bfc-b64c0d11086f.png)

**Comment by benjaminrobinson** [comment]
Same school...Is this a cache issue potentially?

**Comment by gwenrr** [comment]
seems fixed on prod

**Comment by benjaminrobinson** [comment]
This problem exists on other graphs (not just the one displayed below) in this school's equity report:

![image](https://cloud.githubusercontent.com/assets/7928978/6640547/93a1ad86-c96e-11e4-9d9c-90093842bbb4.png)

I wonder if this problem exists on other graphs across the site...might be that the range issue is larger than previously thought.

**Comment by gwenrr** [comment]
yes - lots of problems with the historical data link with DC CAS data (missing percents etc.)
![screenshot 2015-03-13 16 18 54](https://cloud.githubusercontent.com/assets/7264714/6646597/f55173ee-c99c-11e4-95e4-e79ee87020fc.png)
![screenshot 2015-03-13 16 19 11](https://cloud.githubusercontent.com/assets/7264714/6646596/f5508470-c99c-11e4-88fa-e279cff7ae9e.png)

**Comment by mepps** [comment]
![screen shot 2015-03-23 at 10 04 28 am](https://cloud.githubusercontent.com/assets/4406809/6781441/0aff5e00-d144-11e4-86a4-3233b05d8676.png)

![screen shot 2015-03-23 at 10 07 22 am](https://cloud.githubusercontent.com/assets/4406809/6781487/6db9e542-d144-11e4-828e-78dbfca5e343.png)

This is fixed on staging for places where the percentages exceeded the range. 

Gwen, in the second picture, I believe it was a style choice not to include percentages for the DC average.

**Comment by cmgiven** [comment]
Yes, that's correct. Thanks, Maggie.
