### ISSUE TITLE
Accountability/School Classification Exhibit Duplicate Detail Listing and/or Missing Summary

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#109]
In some cases, the summary tab of the Accountability exhibit does not show on the school report card page:
![image](https://cloud.githubusercontent.com/assets/7928978/6358826/7ab53340-bc3c-11e4-8996-83d6d39d3778.png)

and in all others the detail tab of the Accountability exhibit is showing each value two times:

![image](https://cloud.githubusercontent.com/assets/7928978/6358842/8a901910-bc3c-11e4-9b01-c8a16dacf41e.png)

http://learndc.org/schoolprofiles/view?s=0450#reportcard

And I'm viewing this in Google Chrome using Windows 7...

**Comment by benjaminrobinson** [comment]
@mepps any idea why this is happening?

**Comment by mepps** [comment]
Hi Ben, I'm looking into this.

**Comment by mepps** [comment]
This is because we hadn't deleted the school_ files on our end. However, I noticed that DC still doesn't have a specific accountability file. Working on resolving this now.

**Comment by benjaminrobinson** [comment]
You're saying that the state doesn't have an accountability file? I can create that...I should have seen that earlier!  Thanks, @mepps!

**Comment by benjaminrobinson** [comment]
Accountability file for the state has been created and will come along with the next push of data...

**Comment by mepps** [comment]
Awesome Ben! I'm importing the data without the school_ files now for staging. It fixed the issue when I did that import locally.

**Comment by mepps** [comment]
![screen shot 2015-03-09 at 9 16 23 am](https://cloud.githubusercontent.com/assets/4406809/6555492/faba8130-c63c-11e4-892d-df8110e3c399.png)

Fixed on prod.
