### ISSUE TITLE
Source Data: Multiple Exhibits: Malformed JSON on "org_name" and "timestamp"

### ISSUE THREAD

**Issue by psteininger** [DC-OSSE/LearnDC_v2#11]
after each push, between 20 - 50 different exhibits in various org_type/org_code directories have leading and/or trailing new line characters within double quotes. This is not valid JSON and fails when parsing.

I use my IDE to search and replace using the following regular expressions:
```
"([\w\d\s\-\(\)\.]+)\n" replace with "$1"
"\n([\w\d\s\-\(\)\.]+)" replace with "$1" 
````

**Comment by benjaminrobinson** [comment]
@cmgiven:  Many json files do not have a name for the org_name (the org_name creation line is sometimes commented out in the ETL files)...should I add org_names to the ETL file (i.e. take away the comment out and add the gsub language) to all the files or is there a reason some json files do not have org_names?  Thanks!

**Comment by cmgiven** [comment]
I'll defer to @psteininger or @mepps here. Probably not necessary to fix where not broken.

**Comment by benjaminrobinson** [comment]
Would love to get some feedback on this by tomorrow before lunch as I'll be out from lunch to the end of the day at the postsecondary conference!

**Comment by cmgiven** [comment]
Let's go with don't add org_name anywhere it isn't already. We derive org_name form the overview files, and we use school codes for matching, so I believe it's just a nice-to-have for human readability of the files.

**Comment by benjaminrobinson** [comment]
Thanks, Chris.  The only ETL files that have the "org_name" commented out are the school level ETL files in the Enrollment exhibit.  I've implemented the changes we created across all the ETL files so this should be good to go once I make the next commit to GitHub...
