### ISSUE TITLE
Equity Reports - DC CAS historical data

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#110]
Either a mislabeling or a mis-ordering

![screenshot 2015-02-27 09 16 11](https://cloud.githubusercontent.com/assets/7264714/6413860/639c58d8-be61-11e4-8d48-cb75b5ffe327.png)

**Comment by mepps** [comment]
Hi Gwen, Looks like that's the data's orders for the years. I'll add something in the code to order them on the front end. Might be worth working on in the data for the long run since other developers working with the code might assume it would be ordered by year.

**Comment by benjaminrobinson** [comment]
I can run some code to order the data by year if we want to...its just that I need to figure out how to make the CAS code run in less than 6 hours first!

**Comment by mepps** [comment]
![screen shot 2015-02-27 at 5 38 43 pm](https://cloud.githubusercontent.com/assets/4406809/6422512/829c6b1a-bea7-11e4-86bd-bf4fd741cbe1.png)
Fixed on prod in front end.

**Comment by gwenrr** [comment]
Thank you!
