### ISSUE TITLE
School Code 0117 switches between Potomac Lighthouse PCS to Potomac Preparatory PCS when starting on Overview and moving to Report Card

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#111]
Overview example:
![image](https://cloud.githubusercontent.com/assets/7928978/6415644/5dc4a3d6-be6e-11e4-9400-6736300f0600.png)

Report Card example:
![image](https://cloud.githubusercontent.com/assets/7928978/6415654/69989924-be6e-11e4-8e5a-8689ea248250.png)

**Comment by gwenrr** [comment]
To be clear, the right name is Potomac Preparatory

**Comment by gwenrr** [comment]
Looks fixed to me

**Comment by benjaminrobinson** [comment]
Its not.

**Comment by benjaminrobinson** [comment]
![image](https://cloud.githubusercontent.com/assets/7928978/6556546/a52ea3a6-c644-11e4-9c92-c4ada81163af.png)

![image](https://cloud.githubusercontent.com/assets/7928978/6556564/bd99bfc0-c644-11e4-98d2-77322d33c3c9.png)

**Comment by mepps** [comment]
Looking into this.

**Comment by mepps** [comment]
I think I've found why this is happening. The page title is generated by the old json files on the server. I will find where the other titles are generated and make the overview tab call from the same function.

**Comment by benjaminrobinson** [comment]
Good.  Are some other updates to the school overview files that aren't appearing now going to show when you implement this change?  I made updates to some of the school overview files and they haven't shown up since being commushed.

**Comment by mepps** [comment]
I will look into that too.

**Comment by benjaminrobinson** [comment]
Thanks.  I have an example for you that should be able to show you if the new overview files are powering the overview tab information on the site!

What's on the site right now:
http://learndc.org/schoolprofiles/view?s=1206#overview

Associated overview.json file:
https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/school/1206/overview.json

**Comment by mepps** [comment]
@benjaminrobinson can you review the overview tab on staging and let me know if the data looks right now?

**Comment by mepps** [comment]
Also, I don't think we need the id: overview anymore--it may be causing import errors. Sorry, I've learned more about the structure of that exhibit.

**Comment by benjaminrobinson** [comment]
Ok.  I think the Potomac issue has been revised but the example I used above isn't working is that because of the "id:  overview" bit?  Do you want me to remove the whole bit including the id part?  Could you send me a picture of what the JSON should look like so I can copy the formatting?

**Comment by benjaminrobinson** [comment]
I also see that the "Links" section on the Overview tab on staging still includes a link to the non-existant links for the PMF Report Card?  Didn't we want to link that to the Report Card tab or something like that so user could reach the PCSB PMF dashboard site?

**Comment by mepps** [comment]
We can return to this structure:

https://github.com/socialdriver/learndc-data/blob/master/converted/school/1206/overview.json

I apologize as I didn't realize how different this exhibit was from others.

I don't know much about the PMF link on the dashboard, I'll open a new issue to get Chris's input.

**Comment by benjaminrobinson** [comment]
JSON formatting commushed.  Should work better now and the Potomac exhibit should change too once the fix is pushing to production from staging!

**Comment by gwenrr** [comment]
Still has Potomac Lighthouse name on overview page 
![screenshot 2015-03-18 17 37 35](https://cloud.githubusercontent.com/assets/7264714/6720039/ac1e247c-cd95-11e4-806d-8050b945e72f.png)

**Comment by mepps** [comment]
Hey Gwen, haven't pushed the code prod yet, was making sure all the data was correct.

**Comment by cmgiven** [comment]
Look at the grade range for this school: http://stage.learndc.org/schoolprofiles/view?s=1107#overview

Has that code been updated with the new PK3 and PK4 keys?

**Comment by benjaminrobinson** [comment]
That's what I was noticing...PK3 and PK4 have changed but the underlying Java Script needs updating along with everything else.

https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/school/0117/overview.json

**Comment by gwenrr** [comment]
enrollment tab for grade - is only showing all students (is this what you mean?)

**Comment by cmgiven** [comment]
That's the only issue I've found. Everything else looks good.

**Comment by cmgiven** [comment]
Not sure what issue you're observing, Gwen. This is the appearance of "Undefined" in the list of grades on the Overview tab.

**Comment by benjaminrobinson** [comment]
And "undefined" in the instance of Potomac Preparatory PCS are the PK3 and PK4 grades that are still only understood in the overview files as PS and PK and once those are changed and implemented on the site will show correctly...Right, @cmgiven and @mepps?

**Comment by cmgiven** [comment]
That's my understanding, yes.

**Comment by mepps** [comment]
I have a fix for the overview tab "undefined" values that is live on staging now.

**Comment by benjaminrobinson** [comment]
I'm not seeing the fix implemented on staging...I'm using Firefox and Windows 7 to view the staging site...here's an example:

![image](https://cloud.githubusercontent.com/assets/7928978/6966598/45a61210-d928-11e4-8935-df425037bc34.png)
