### ISSUE TITLE
Name Changes for 6 PCS Schools

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#112]
I don't think this happens on my end or does it?

-  Change Name of School Code 0106 to Community Academy PCS - Amos 5
-  Change Name of School Code 1206 to E.L. Haynes PCS - Elementary School
-  Change Name of School Code 1138 to E.L. Haynes PCS - High School
-  Change Name of School Code 0146 to E.L. Haynes PCS - Middle School
-  Change Name of School Code 0160 to Hospitality High

**Comment by cmgiven** [comment]
It does. School names are set in the overview files.

**Comment by benjaminrobinson** [comment]
Should be changed with the next push!
