### ISSUE TITLE
acgr pullouts for some schools showing 5yr instead of 4yr rates

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#113]
![screenshot 2015-03-02 14 06 28](https://cloud.githubusercontent.com/assets/7264714/6448084/6b9a9636-c0e5-11e4-968e-085e42111cd0.png)
![screenshot 2015-03-02 14 06 11](https://cloud.githubusercontent.com/assets/7264714/6448085/6b9b6ec6-c0e5-11e4-9b6c-6eddbdfafc74.png)

Other examples include 0450, 0153, 0186, 0101, 0161

**Comment by gwenrr** [comment]
This is happening both on ER and on report card for these schools

**Comment by gwenrr** [comment]
add sc = 0163 to this list

**Comment by gwenrr** [comment]
Can I get an ETA about when this might be fixed - we are working on ACGR public release. Thanks.

**Comment by cmgiven** [comment]
The pull-out issue has been resolved. @mepps is currently troubleshooting the dashboard icon, but it seems likely that we'll be able to resolve that issue today.

**Comment by gwenrr** [comment]
Thank you - please keep me posted, if possible.

**Comment by cmgiven** [comment]
Will do.

**Comment by mepps** [comment]
![screen shot 2015-03-04 at 10 06 36 am](https://cloud.githubusercontent.com/assets/4406809/6486053/2a7305b8-c256-11e4-9ba3-6c0c388ba09a.png)

Resolved on prod.

**Comment by cmgiven** [comment]
Confirmed. We're good to go here, Gwen.
