### ISSUE TITLE
ACGR IDEA PCS (SC = 0163) not showing

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#114]
No data showing (and pullout likely showing 5yr data) although you can download with the download button

![screenshot 2015-03-02 14 16 31](https://cloud.githubusercontent.com/assets/7264714/6448293/e6477452-c0e6-11e4-8bbc-aefb62936d2f.png)

**Comment by mepps** [comment]
![screen shot 2015-03-02 at 2 33 44 pm](https://cloud.githubusercontent.com/assets/4406809/6448603/278832ba-c0e9-11e4-9afe-175e3f438337.png)

Fixed on prod.
