### ISSUE TITLE
one more ACGR - Richard Wright sc=3067

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#115]
graduation exhibit should be hidden on report card (it is already hidden on equity report)

school only goes to 11th grade

![screenshot 2015-03-02 17 42 53](https://cloud.githubusercontent.com/assets/7264714/6452436/b57eaecc-c103-11e4-8009-9b7b54b1122d.png)

**Comment by cmgiven** [comment]
This is a data issue. The data file shows a 2014 cohort of 11 students, none of whom graduated.

https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/school/3067/graduation.json

**Comment by gwenrr** [comment]
Ben - please change the suppression to n<25

**Comment by gwenrr** [comment]
Would it be possible to hide this exhibit for this year instead?

**Comment by cmgiven** [comment]
This is defined by the presence of a data file. We can hide by removing the data.

**Comment by benjaminrobinson** [comment]
Will this and #117 both require a git rm...or just an addition to the .gitignore or both?  We don't want to completely remove the graduation exhibit for these schools since we expect them to have graduation exhibits in the future.  Hope everyone is doing OK in the wake of the winter storm!

**Comment by cmgiven** [comment]
Both (remember: `git rm`, commit the removal, add to `.gitignore`, commit the changed `.gitignore`). When you're ready to restore, just remove from the `.gitignore` and make a new commit.

**Comment by gwenrr** [comment]
Thanks, @cmgiven and @benjaminrobinson

**Comment by benjaminrobinson** [comment]
This will go up with the next push of data.
