### ISSUE TITLE
IDEA PCS's (School Code 0163) Enrollment Equity Report Exhibit Not Showing Data

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#116]
![image](https://cloud.githubusercontent.com/assets/7928978/6486510/87854e98-c259-11e4-8c4d-26249183befd.png)

**Comment by mepps** [comment]
![screen shot 2015-03-04 at 11 14 48 am](https://cloud.githubusercontent.com/assets/4406809/6487532/b3c29938-c25f-11e4-9c97-600523893340.png)

It was a cache issue and it's fixed on prod.
