### ISSUE TITLE
Eastern HS (sc=457) ACGR report card exhibit

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#117]
Can we hide this for this year? It says 0%. Eastern did not have a 9th grade class in SY2010/2011, so a four-year graduation rate is not possible.

The other alternative would be for the exhibit to say N/A.

But this school will eventually have a graduation rate. Just not this year.

**Comment by cmgiven** [comment]
This is set by the data files. Currently there's a cohort of 27 students with 0 graduates.
