### ISSUE TITLE
dowload data button - enrollment 

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#118]
Something weird is going on with the download data button - it is missing the actual numbers.

I clicked on download from the enrollment exhibit on the profile - and the columns I got were org type, org code, grade, year, subgroup - but no actual numbers of enrollees.

Hmmm.
![screenshot 2015-03-06 15 46 12](https://cloud.githubusercontent.com/assets/7264714/6536038/fbc60300-c417-11e4-9744-c1de5f357e26.png)

**Comment by benjaminrobinson** [comment]
JSON API calls are working fine but the CSV call is where the issue is...

**Comment by mepps** [comment]
It looks like it's just this exhibit. @psteininger it's going to this url: https://learndc-api.herokuapp.com/api/exhibit/enrollment.csv?s[][org_type]=school&s[][org_code]=0452

**Comment by mepps** [comment]
I think the issue is that the data is structured slightly differently than the other downloaded exhibits. Because the others have multiple values in val and enrollment has only one. We will have to add handling for this. @psteininger let me know if you have any thoughts on that.

**Comment by mepps** [comment]
Nevermind, it's resolved. I just need to push the fix live.

**Comment by mepps** [comment]
![screen shot 2015-03-09 at 11 33 08 am](https://cloud.githubusercontent.com/assets/4406809/6558065/1686bc0e-c650-11e4-8a2c-448c5fccf662.png)

Attached screenshot is from prod. Fixed.
