### ISSUE TITLE
Do the CSV Files in the Export Folder Serve a Purpose?

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#120]
Was just wondering about the CSVs in the Export folder...I have updated some of them recently but I'm unsure of what purpose they serve other than that the data is available in CSV format.  We have a space on the OSSE website for commonly requested datasets so if that was the purpose I think we've decided that that is where they should lie.

http://osse.dc.gov/publication/commonly-requested-data

**Comment by gwenrr** [comment]
The purpose is so someone looking at Learn DC doesn't have to go somewhere else to download the data

**Comment by benjaminrobinson** [comment]
Where do these files appear on LearnDC proper?  All the data download buttons are just links to the API set to show CSVs instead of JSON.  The CSVs in the GitHub repo do not really do anything except sit there, which is why I was asking if they were necessary at all in that respect.

**Comment by cmgiven** [comment]
These files are not consumed by LearnDC. They were created by Alex as a test of the new ETL.
