### ISSUE TITLE
Formatting: HQT Classes has two different keys school_entity and school_category

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#121]
@benjaminrobinson can these all be school_category?

**Comment by benjaminrobinson** [comment]
Yes...Not sure why I called those that.

**Comment by benjaminrobinson** [comment]
This has been commushed (that hybrid word I made up yesterday) on our end...

**Comment by mepps** [comment]
Awesome. Re-trying the import.

**Comment by mepps** [comment]
Thanks, Ben! The import on my local machine went smoothly this time.

**Comment by benjaminrobinson** [comment]
:smiley:
