### ISSUE TITLE
PMF Link on Dashboard

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#122]
@benjaminrobinson I also see that the "Links" section on the Overview tab on staging still includes a link to the non-existant links for the PMF Report Card? Didn't we want to link that to the Report Card tab or something like that so user could reach the PCSB PMF dashboard site?

@cmgiven Any thoughts on the link on the dashboard?

**Comment by cmgiven** [comment]
This looks like a data issue. If you look in overview.json, you can see that the old values are still appearing there under the key "external_report_card". Ben, once you update this to mirror the pcsb_pmf exhibit, the site will be updated as well.

**Comment by benjaminrobinson** [comment]
Got it!  Thanks, Chris!

**Comment by benjaminrobinson** [comment]
Tommy wrote some code to put the PMF data in the overview file and I can just earth that up and reuse it here.  I'll send you both a sample overview.json file to see if it fits what we're looking for, OK?

**Comment by mepps** [comment]
Perfect Ben!
