### ISSUE TITLE
Front-end: Grade filter on school search page does not work

### ISSUE THREAD

**Issue by cmgiven** [DC-OSSE/LearnDC_v2#123]
Searching for Pre-Kindergarten only returns a single school. Should include many others. Possibly related to the capitalization changes from a while back (numbered grades work fine)?

http://www.learndc.org/schoolprofiles/search

**Comment by benjaminrobinson** [comment]
I'm seeing the same thing but Kindergarten looks to be working fine (I'm also looking at the staging site)...maybe related to the key changes related to the PS/PK switch to PK3/PK4 (or whatever the translation is exactly)...

**Comment by mepps** [comment]
Ben you're correct, it's the key change. This is what it's looking for:

"PS": { "name": "Enrollment: Preschool" }, "PK": { "name": "Enrollment: Pre-Kindergarten" }, "KG": { "name": "Enrollment: Kindergarten" }

We could change the filter to PK3/PK4, if that's consistent throughout the data.

**Comment by benjaminrobinson** [comment]
It should be now, especially in the school overview files!  Will look into what's going on with the Walker Jones Early Stages file since it is showing up in the filers but nothing else is...

**Comment by benjaminrobinson** [comment]
Walker Jones Early S.T.A.G.E.S. (school code 6000) doesn't have a folder in the Export/JSON/school directory so that must be happening on the Social Driver side?

**Comment by mepps** [comment]
Looks like we have that file in our repo: https://github.com/socialdriver/learndc-data/tree/master/converted/school/6000

@benjaminrobinson and @cmgiven do you know the history of this school being in the data?

**Comment by cmgiven** [comment]
I do not, no. The commit is dated data as of Nov 3, but the school was not present in the OSSE repo on that date. Perhaps it's a holdover from older data?

@benjaminrobinson, should this school be deleted?

**Comment by benjaminrobinson** [comment]
I'm not sure...its something that I'd have to ask Jeff or @gwenrr about but if I had to guess it would be yes.  Walker Jones Early S.T.A.G.E.S is an early childhood special education school so it doesn't have a lot of data to begin with but I'll get back to you all on that!

**Comment by benjaminrobinson** [comment]
Same question about Maya Angelou Academy at New Beginnings (formerly Oak Hill), which is school code 0860...looks like it is a similar story to Walker Jones in that it has a school_overview and a staff_degree file on Social Driver's end but not on OSSE's end...Just bringing this back to people's attention!

**Comment by mepps** [comment]
I have a fix for the grade filter live on staging. Let me know if it's working correctly.

**Comment by benjaminrobinson** [comment]
Looks like the grade filter is working!
