### ISSUE TITLE
School performance levels not showing on DC CAS exhibit

### ISSUE THREAD

**Issue by cmgiven** [DC-OSSE/LearnDC_v2#124]
See http://www.learndc.org/schoolprofiles/view?s=1100#reportcard for example.

Using the Detail view of the DC CAS exhibit, switch the Display to Performance Levels. We can see the performance levels for the state, but not the school.

**Comment by gwenrr** [comment]
There also are no composition or science scores, which there should be, right?

**Comment by mepps** [comment]
This is happening because in the state files there is a key "advanced" but this doesn't exist in the school files which only have "proficient_or_advanced" and "proficient".

**Comment by mepps** [comment]
@cmgiven @benjaminrobinson Should I use proficient_or_advanced? My guess is that that would be the wrong data for this visualization.

**Comment by benjaminrobinson** [comment]
Let me look into this...I think the LEA JSON files have advanced as a part of the key while the school JSON files do not.  This is just a simple fix that I can implement in the school DCCAS ETL but I need to do some snooping first!

**Comment by benjaminrobinson** [comment]
This is definitely where the problem lies...I incorrectly numbered the key/value index to generate the JSON files.  Regenerating and will commush as soon as you'd like.

**Comment by benjaminrobinson** [comment]
Do we need the new school level dccas.json files commushed in order for the data visualization documentation piece to be final?  I can do that as soon as you'd like...

**Comment by cmgiven** [comment]
No, we just faked it. The data visualization guide was submitted this morning.

**Comment by benjaminrobinson** [comment]
Ah...I did not receive that.  The LEA DC CAS Exhibit had the visualization that worked but the school side obviously did not.  Great catch, @cmgiven and @mepps!

**Comment by benjaminrobinson** [comment]
Well...whenever we commush the next update this will be included so I'll close it so its not haunting us in the meantime.
