### ISSUE TITLE
HQT Table inclusion of Poverty Quartile

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#125]
Just wanted to put this in there since I brought it up in our meeting yesterday but didn't have a lot of time to think about more deeply.  I think it would be good to report on the high and low poverty quartiles for each of the schools and since the designation is in the data.  I remember @mepps said that it would be difficult to do because of the difference in the name of the variable in the JSON files.  Would that be possible to change if I changed the name of teacher_category to school_category so that the variables matched up?  I know the main issue with reporting HQT classes was that they wanted us to do it by poverty quartile.  Thought this would be a good place to host the discussion around any potential changes to the data as well as any thoughts about the guidance from @cmgiven or @gwenrr!  Thanks!  This is Anacostia HS (school code 0450, by the way)...

![image](https://cloud.githubusercontent.com/assets/7928978/6920398/03b3ffb8-d78c-11e4-8dfc-5954a8b9518c.png)

https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/school/0450/staff_degree.json
https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/school/0450/hqt_classes.json

**Comment by benjaminrobinson** [comment]
There is also no mention of the year, which in the files I called it 2014 but maybe it should be 2013?  Not sure what to think here.  @gwenrr or @cmgiven, do you have any thoughts on whether this 2013-2014 data should have the year designation of 2013 or 2014?

**Comment by cmgiven** [comment]
We default to the most recent year with the exception of enrollment, where it's the audit year. That would be the starting point, although it's open to discussion.



—

**Comment by benjaminrobinson** [comment]
I have no preference, I was just wondering what everybody else was thinking!

**Comment by cmgiven** [comment]
Per decision on the call, we do not need to identify the poverty quartile of a given school.
