### ISSUE TITLE
State values in tables comparison data

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#127]
@benjaminrobinson @cmgiven In the school report cards Highly Qualified Teacher table, should that be compared against state data by type of school (middle, secondary, etc) or by poverty quartile? Note, if by poverty quartile, we might have to restructure the data.

**Comment by benjaminrobinson** [comment]
Could we do both?  Let's talk tomorrow by phone if you have time about any potential data restructuring that may have to occur!

**Comment by mepps** [comment]
It will be challenging to do both without really redoing the styling, but let's talk tomorrow afternoon. Thanks Ben!

**Comment by gwenrr** [comment]
I think I need to be involved in this conversation before any decisions are made. I would like to understand better what is being proposed here and its implications before moving forward. Thank you.

**Comment by mepps** [comment]
@gwenrr would you like to be part of a phone conversation tomorrow?

The challenge is that the data is broken up by both grade levels (Secondary vs Elementary) and poverty quartile (low vs high). At the school level, the data keys are separated into school category and poverty quartile. However, for LEAs and state data, the key is just school category for both grade level and poverty quartile.

The question is whether we compare the school data against data for all other schools at the same poverty quartile or at the same grade level. I would suggest grade level, based on how the data is structured, and also how people would generally think about the data, but it is definitely your decision.

Let me know if you have any questions. Thanks!

**Comment by benjaminrobinson** [comment]
Let's talk tomorrow but a restructuring of the data on my end to make all the files look more like the school level hqt_ classes.json files is not a problem...

**Comment by mepps** [comment]
Sounds good. I'll think through the implications of that on my end too.

**Comment by gwenrr** [comment]
My day is pretty loaded already so I cannot participate in a call. I just don't want a lot of work (on our end, your end, or Collaborative's end) to be put into this without having a few minutes more to think about it. Thank you.

**Comment by mepps** [comment]
@gwenrr that makes sense. I have it working where with the data as is, and we can pause until Monday otherwise.

**Comment by mepps** [comment]
@cmgiven

**Comment by mepps** [comment]
It sounds like we need to compare schools against all data for the state.

**Comment by cmgiven** [comment]
Closing this to move discussion to #133.
