### ISSUE TITLE
Remove duplicate state column

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#132]

**Comment by mepps** [comment]
![screen shot 2015-04-07 at 10 26 06 am](https://cloud.githubusercontent.com/assets/4406809/7025271/8a9d62c4-dd10-11e4-9f70-61585e50de1f.png)

Fixed in staging. thought it was duplicative to say DC with only one column but can change that.

**Comment by cmgiven** [comment]
This works for me.
