### ISSUE TITLE
teachers - statement about provisional / emergency licenses - state report card only

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#134]
We need to make sure this statement is not (again) dropped (we have had it on the site before - and needs to be included - it's part of federal requirement)

"No teachers have emergency or provisional credentials."

**Comment by cmgiven** [comment]
Would it be possible to include everywhere? This would be easier than just including on the state, but let us know if that doesn't work.






On Monday, Apr 6, 2015 at 4:14 PM, gwenrr <notifications@github.com>, wrote:

We need to make sure this statement is not (again) dropped (we have had it on the site before - and needs to be included - it's part of federal requirement)


"No teachers have emergency or provisional credentials."

**Comment by mepps** [comment]
It would be really easy for it just to be on state and LEA.

**Comment by gwenrr** [comment]
Looking at the guidance - I guess it needs to be on both. Thank you!

**Comment by cmgiven** [comment]
Text is up now on staging. Inserted where I thought it made the most logical sense, but check out both the school and LEA/state versions and let me know if something else would work better.

**Comment by gwenrr** [comment]
Looks good. It's one of those check-off-the-reporting-box things and not worth a huge time investment. Thank you, Chris.
