### ISSUE TITLE
Staff degree: teacher category changed to school_category

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#136]
@benjaminrobinson was this key change on purpose and will it continue to future data imports? It requires changing the api schema. I'm not sure if you were trying to follow what I suggested, but I was only referring to changing the keys in hqt_classes. thanks!

**Comment by benjaminrobinson** [comment]
Woops!  I can change it back but I figured it would make sense to call the variable the same thing so I changed the key...Don't want to be too burdensome.

**Comment by mepps** [comment]
I understood it to mean something different anyways. What really matters is consistency, and I think it probably makes sense to keep that key as it was.

**Comment by benjaminrobinson** [comment]
So go back to calling it teacher_category?

**Comment by mepps** [comment]
Yes, thanks!
