### ISSUE TITLE
Staff degree LEA 0000

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#137]
https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/lea/0000/staff_degree.json

@benjaminrobinson There's a string in here causing it to be non-valid json. As an update, for some reason the data isn't importing and I'm trying to track down why.

**Comment by benjaminrobinson** [comment]
That's a weird file...not sure how that was created but will commit a new one.
