### ISSUE TITLE
LEA: 0129?

### ISSUE THREAD

**Issue by psteininger** [DC-OSSE/LearnDC_v2#139]
does this LEA still exist? It is in SD repo but not in DC-OSSE one

**Comment by psteininger** [comment]
I take that back... I got cross-eyed looking in schools in one spot and leas in the other. HOWEVER... the dccas.json for LEA 129 is empty (file is there but no data). What should we do?

**Comment by psteininger** [comment]
Since this is the only dccas.json changed in this load, I will assume it's non-intentional and not overwrite in learndc-data repo. 

I pushed the changes and kicked off the import. As soon as it is successfully completed, it will be accessible via staging site

**Comment by benjaminrobinson** [comment]
Hmm...that's weird.  Thanks for the update Piotr.  My local copy of the repo has a JSON file with data in it for that LEA.  Not sure what's going on but I think you did the right thing.  Thanks for the heads up!

![image](https://cloud.githubusercontent.com/assets/7928978/7231240/306efcf4-e742-11e4-88e3-660e971f2153.png)
