### ISSUE TITLE
HQT / credential exhibit - no SY listed

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#140]
I am sorry - but I just noticed that, unlike other exhibits on the site, this one does not say which school year these data are for (2014). Is there an easy way to add that? Thanks.

**Comment by benjaminrobinson** [comment]
That data element is in the data so it should be just a matter of finding a place to add it in...

**Comment by cmgiven** [comment]
Good catch, Gwen. I have added this information to the description for the time being. However, we may want to explore adding that to the table headers in the near future. But hopefully this can keep LEA review on track.

Leaving this issue open for continued discussion,

**Comment by gwenrr** [comment]
Thank you.
