### ISSUE TITLE
Special Ed Exhibit API Link

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#141]
For some reason, the link to the API for the Special Ed exhibit has *special_id* instead of *special_ed*...this should be easily fixed

Example can be found on the DC LEA page on staging...not sure how systemic this is.  The special_ed data is there just the API link for the data download button just isn't showing there.  I'll assign @psteininger since Maggie's on a well deserved vacation this week!

http://stage.learndc.org/schoolprofiles/view?s=lea-0001#profile
https://learndc-api.herokuapp.com//api/exhibit/special_id.json?s[][org_type]=lea&s[][org_code]=0001

**Comment by mepps** [comment]
Fixed on both prod and staging.

**Comment by benjaminrobinson** [comment]
Thanks, @mepps!  Welcome back!  Hope you had a great vacation!
