### ISSUE TITLE
LEAs with no schools in the High or Low Poverty Quartile (i.e. "Middle" Quartiles schools)

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#142]
I think this may be a simple JavaScript coding workaround but we're getting some feedback from LEAs on the issue where LEAs that do not have schools in either the low or high poverty quartiles (i.e. only have a value for middle and not for the other two quartiles) in the HQT exhibit.  Is there a way to filter out the exhibit for these LEAs to only show the 'All Schools'.  @cmgiven or @mepps, please let me know if this is confusing or not intuitive!

Here's an example below and all the schools that I believe fit this description below.

http://stage.learndc.org/schoolprofiles/view?s=lea-0132#reportcard
https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/lea/0132/hqt_classes.json

lea_code                                       lea_name
       104                        ARTS AND TECHNOLOGY PCS
       106                       BOOKER T. WASHINGTON PCS
       107                                    BRIDGES PCS
       109                               CESAR CHAVEZ PCS
       114                             D.C. BILINGUAL PCS
       117                              EAGLE ACADEMY PCS
       118                    EARLY CHILDHOOD ACADEMY PCS
       122                                HOSPITALITY PCS
       123       CEDAR TREE ACADEMY PUBLIC CHARTER SCHOOL
       125                          PERRY STREET PREP PCS
       126                                       IDEA PCS
       127                              IDEAL ACADEMY PCS
       129                                    KIPP DC PCS
       132                       MARY MCLEOD BETHUNE  PCS
       135                                   MERIDIAN PCS
       139                        POTOMAC PREPARATORY PCS
       140                                      ROOTS PCS
       142                      SEED PCS OF WASHINGTON DC
       145                              THE NEXT STEP PCS
       146                  THURGOOD MARSHALL ACADEMY PCS
       147                               TREE OF LIFE PCS
       152 WASHINGTON MATHEMATICS SCIENCE TECHNOLOGY PCHS
       153                         WILLIAM E. DOAR JR PCS
       155            ACHIEVEMENT PREPARATORY ACADEMY PCS
       158                              EXCEL ACADEMY PCS
       163            NATIONAL COLLEGIATE PREPARATORY PCS
       175                                   SOMERSET PCS
     4002                                           DYRS

Thanks!

**Comment by mepps** [comment]
Thanks Ben! I'll look into this.

**Comment by benjaminrobinson** [comment]
Thanks, @mepps!  I'll get back to you on #130 today since I will (just me!) be out of the office on Thursday and Friday! Thanks again!  Glad you're back!

**Comment by mepps** [comment]
@benjaminrobinson @cmgiven The easiest way to fix this would be not to display sections if the total number of teachers overall is 0 (I previously added logic to display these values as 0). Does this sound correct to you?

**Comment by mepps** [comment]
@benjaminrobinson @cmgiven Any thoughts on this? I have the code change ready to go if you're comfortable with the logic from your knowledge of the data. I'm happy to explain on the phone if needed.

**Comment by cmgiven** [comment]
This makes sense to me and is indeed what I'd recommend. @benjaminrobinson, does this address the issue?

**Comment by benjaminrobinson** [comment]
I think this would solve the issue...does the end result mean that after implementing this code change, the LEAs mentioned above would only show the "All Schools" section and any other LEAs that for example have schools in the "Low-Poverty" quartile but no schools in the "High-Poverty" quartile would only have the "All Schools" and "Low-Poverty" sections showing?  If that is the case, then I'm sold!

**Comment by benjaminrobinson** [comment]
Is this the case, @mepps or @cmgiven?

**Comment by cmgiven** [comment]
That's my understanding, yes.

**Comment by benjaminrobinson** [comment]
Great.  That works then!

**Comment by mepps** [comment]
I've pushed this fix to staging (this lea has no high-poverty schools for example).

![screen shot 2015-05-06 at 5 47 42 pm](https://cloud.githubusercontent.com/assets/4406809/7504417/06068d00-f418-11e4-9078-57d02ca8efde.png)
