### ISSUE TITLE
Years on DCPS and PCS LEA Page are not Formatted Correctly

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#143]
![image](https://cloud.githubusercontent.com/assets/7928978/7499598/cdfb9002-f3f6-11e4-9aac-dc1304de0a1c.png)

![image](https://cloud.githubusercontent.com/assets/7928978/7499610/e410b840-f3f6-11e4-97d9-2e6f8dac3ffe.png)

**Comment by gwenrr** [comment]
That's funny - I just noticed that on the state page, as well (though I do know why @benjaminrobinson and I are looking at this) 
![screenshot 2015-05-06 13 09 22](https://cloud.githubusercontent.com/assets/7264714/7499686/4ef92f84-f3f7-11e4-8b75-97dec27a413c.png)

**Comment by mepps** [comment]
I will look into this.

**Comment by mepps** [comment]
This is an issue with the import that is currently promoted. In looking at the staging site, it is not an issue, so as soon as we promote the latest data it should be resolved:

![screen shot 2015-05-06 at 3 11 49 pm](https://cloud.githubusercontent.com/assets/4406809/7501494/438164a4-f402-11e4-9d84-41a42bdbef1e.png)

**Comment by benjaminrobinson** [comment]
I think we're seeing some other issues around the site with the latest data not being promoted:  specifically around the PCSB PMF Links in the school overview tab and with the DCCAS exhibit not appearing on the live site's school report card tab.

**Comment by mepps** [comment]
@benjaminrobinson it looks like the next data we could import has the restructured staff_degree exhibits, so would mess up the instructional staff exhibit on the front end. How is the review period going?

**Comment by benjaminrobinson** [comment]
The review period ends on the 19th of May and then I need to do some more data cleaning and put together the data from the LEAs who submitted in this call for revisions (along with some submitting complete data for the '13-'14 school year just now) so I'm hoping to get things squared away within the next 2-3 weeks and fit in the enrollment data (once we deal with this last important but small issue about economically disadvantaged students) in the same fell swoop.

The exhibits and data pieces that I mentioned above (PMF links on the overview and the CAS exhibit) look fine on the staging site but somehow the live site is not displaying them correctly...that's the observation we're making!

**Comment by mepps** [comment]
@benjaminrobinson @gwenrr Attaching screen shot of this resolved in production so closing this.
![screen shot 2015-07-02 at 11 34 26 am](https://cloud.githubusercontent.com/assets/4406809/8480894/5465dd4e-20ae-11e5-81b7-94955d3229fb.png)

**Comment by benjaminrobinson** [comment]
Seeing this on the main page too but not on staging for the DC enrollment audit exhibit in the school profiles. @aaditya-madala @psteininger

**Comment by benjaminrobinson** [comment]
Just for everyone's information this issue does not show in the All Grades, All Subgroups but just (that I can see) within All Grades, Economically Disadvantaged.

![image](https://cloud.githubusercontent.com/assets/7928978/10617498/e51ce5ae-7738-11e5-8f82-3bee35e788a2.png)
