### ISSUE TITLE
more on Briya PCS

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#145]
There is clearly more going on with Briya data flow. Data appear missing for PK4 on the prod site. In addition, grade level data on Equity Report also missing.

![screenshot 2015-05-26 13 12 26](https://cloud.githubusercontent.com/assets/7264714/7818576/a6d24962-03aa-11e5-985a-fa11a2beab69.png)
![screenshot 2015-05-26 13 12 06](https://cloud.githubusercontent.com/assets/7264714/7818577/a6d513e0-03aa-11e5-89ca-756f64bf6032.png)

**Comment by mepps** [comment]
I'm going to close this because this conversation is ongoing in #144. We believe this to be resolved, but @benjaminrobinson is looking over the data now.
