### ISSUE TITLE
Data download button unexcused absence

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#146]
@benjaminrobinson "When I'm looking at the production site's API call for the Unexcused Absences part of the attendance exhibit (along with ISA), the data download button call to the API is calling the attendance exhibit instead of the unexcused_absences data...Just another thing OI noticed if that helps!"

@benjaminrobinson can you tell me which attendance exhibit this is? Equity reports/profile/report card?

**Comment by mepps** [comment]
Realized it wouldn't be equity reports

**Comment by mepps** [comment]
I found it. The challenge here is that this exhibit works differently from the others. The others display the same data multiple ways, where as this one in changing the tab you change what data is displaying and which exhibit it's grabbed from. I may have to think a bit longer about a fix.

**Comment by benjaminrobinson** [comment]
Thanks for digging back into this!

**Comment by mepps** [comment]
Closing this because it will be resolved by #155.

**Comment by benjaminrobinson** [comment]
Two birds, one stone (don't think about it)...Thanks, @mepps!
