### ISSUE TITLE
HQT Numbers not adding up

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#147]
Numbers with highly qualified teachers and non not adding up correctly, see: https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/state/DC/hqt_classes.json

and

https://github.com/DC-OSSE/LearnDC_v2/blob/master/Export/JSON/lea/0001/hqt_classes.json

        "val": {
            "num_total_classes": 4561,
            "num_hq_classes": 3662,
            "num_nhq_classes": 1346
        }
3662+1346 = 4708 not 4561, and so percentages are off

@benjaminrobinson 

Let me know if it's supposed to be this way. Thanks!

**Comment by benjaminrobinson** [comment]
Looking into it...its an aggregation issue so let me do some investigating!

**Comment by benjaminrobinson** [comment]
Caught the problem...nasty little bugger!  Will re commush the data as soon as I re-run all the aggregators and ETL for the HQT exhibit!  Thanks, @mepps!  Good catch!

**Comment by mepps** [comment]
@benjaminrobinson Awesome! Let me know when it's up

**Comment by benjaminrobinson** [comment]
I made the commush about 15 minutes ago so we're good to go!
