### ISSUE TITLE
Display school data by school level

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#148]
@benjaminrobinson this change is pushed, can you take a look? Here's an example:

http://stage.learndc.org/schoolprofiles/view?s=0198#reportcard

But also look at other pages to make sure nothing is wrong. So far in my checks it looks fine. Thanks!

**Comment by benjaminrobinson** [comment]
Can do!  Just got into the office but I'm taking a look at it right now...

**Comment by benjaminrobinson** [comment]
Things look good across schools that have more than one school_category for the HQT exhibit!  Great work, @mepps!
