### ISSUE TITLE
DC Report Card Attendance Exhibit

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#149]
We've received word from Tembo that the DC Report Card Attendance Exhibit, specifically the data for ISA is incorrect...not sure who this is on but apparently the data for that element should read 91% instead of 95%.  Looking into it, I found that the data was hard coded in by Tommy or Alex and sent to you all as a fully made JSON.  This JSON is one of the files that does not appear in the OSSE repo and was one of the many files generated on the OSSE side and sent over to Social Driver for them to do with it as they will.  I know its not best practice but could @mepps or somebody go into the repo and change .95 to .91?

![image](https://cloud.githubusercontent.com/assets/7928978/8135583/4ef8fd44-1106-11e5-9d89-12ccd1e097e7.png)

https://github.com/socialdriver/learndc-data/blob/master/converted/state/DC/attendance.json

**Comment by benjaminrobinson** [comment]
Just wondering if people have seen this!

**Comment by benjaminrobinson** [comment]
@psteininger since Maggie is out of town?

**Comment by mepps** [comment]
@benjaminrobinson I will look into this this afternoon. Thanks!

**Comment by mepps** [comment]
@benjaminrobinson made this change in the file and importing now

**Comment by benjaminrobinson** [comment]
:+1:

**Comment by mepps** [comment]
This is fixed in the latest data on staging.
