### ISSUE TITLE
Roosevelt Stay Has Grade 09 but no other?

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#150]
In new overview file, roosevelt has grade 09 added to accepted and serviced but only other grade is AO. Wanted to make sure this was correct @benjaminrobinson

**Comment by mepps** [comment]
school code 0456

**Comment by gwenrr** [comment]
Seems like Roosevelt STAY is AO. But seems like Ballou STAY has some grades. Looking at this, I'm not sure I trust what is on the prod site. Ballou STAY shows enrollment in 9 (through 2010), 10 (also through 2010) and 12 (through 2008). Nothing for 11. @benjaminrobinson - probably worth checking in with Stephanie about this

**Comment by mepps** [comment]
@benjaminrobinson can we close this in favor of #153?

**Comment by benjaminrobinson** [comment]
I can dig it...
