### ISSUE TITLE
Eastern HS Rising to Rising Priority

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#151]
Only change Eastern HS was Rising to Rising Priority. Are these different categories and is this correct (not sure how that data is used)? @benjaminrobinson

**Comment by mepps** [comment]
school code 0457

**Comment by benjaminrobinson** [comment]
It went from Rising Priority back  to Rising...weird situation but it is correct. That is the only accountability.json file that should have changed.

**Comment by mepps** [comment]
Yes sorry in accountability, great it's staged
