### ISSUE TITLE
Compare Schools Function Broken?

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#154]
Seems like something's rotten in the state of the comparison tool on LearnDC...

![image](https://cloud.githubusercontent.com/assets/7928978/8309889/ce169f2c-199a-11e5-8162-42266401eda8.png)

**Comment by benjaminrobinson** [comment]
Or @mepps?

**Comment by mepps** [comment]
@benjaminrobinson This will a require a deeper dive, but it looks like the js for the comparison tool wasn't updated since some data schema changes took place. I should be able to update on this tomorrow morning. Thanks!

**Comment by benjaminrobinson** [comment]
Great!  Phew...thought it might be something worse.  Thanks for the quick feedback!

**Comment by cmgiven** [comment]
Looks like the same issue (?) is affecting the school search page's filters. Changing any of filters other than grade or location gives no results.

**Comment by benjaminrobinson** [comment]
Just as an FYI, I'll be out of the office for the rest of this week so I won't see if anything happens but please continue trying to fix this issue.  I know that there have been some rumblings among folks about the comparison tool not working...

**Comment by mepps** [comment]
@cmgiven @benjaminrobinson Just an update that I'm looking into this. It seems to be an issue with the api not being updated for the schools call since the data schema changed. Will communicate here when it's resolved.

**Comment by mepps** [comment]
@cmgiven @benjaminrobinson @amberleyromo The comparison tool and the sidebar tool are back up and running. I just still need to look at subgroup names because I think that may still be an issue.

**Comment by mepps** [comment]
@cmgiven @benjaminrobinson @amberleyromo And a final update that I have changed all the subgroup keys to be consistent with the latest data. Feel free to take a look now and let me know if you see any more issues.

**Comment by mepps** [comment]
@benjaminrobinson @cmgiven I'm closing this based on my testing. Let me know if you see anymore issues.
