### ISSUE TITLE
Unexcused absences - school & state report cards

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#155]
We would like to hide this tab entirely for all schools and on the state report card
What would that require?

**Comment by mepps** [comment]
@gwenrr Would this be a good agenda item for our check in next week or is more urgent?

**Comment by gwenrr** [comment]
Not sure we will have a check in next week (scheduling and other issues). Is this something you could proceed on without one?

**Comment by mepps** [comment]
@gwenrr Do you want this hidden forever or for a shorter period of time? I ask because it will change how I hide it. I can schedule this for next week without the check in, but how long you want it hidden is very important to how it's done. Thanks!

**Comment by gwenrr** [comment]
@mepps: I cannot imagine a scenario where we would want to display this again. Please hide forever, and let's hope I don't regret saying this!

**Comment by mepps** [comment]
@gwenrr This change is deployed on staging. Let me know if it looks how you expected before we move it to production. Thanks!

**Comment by mepps** [comment]
@gwenrr @benjaminrobinson Just wanted to follow up on this before the holiday weekend. Would you like me to deploy this tomorrow? Thanks!
