### ISSUE TITLE
St. Coletta PCS LEA Staff Degree Exhibit

### ISSUE THREAD

**Issue by benjaminrobinson** [DC-OSSE/LearnDC_v2#156]
For some reason, St Coletta PCS's LEA profile page has data showing despite no JSON file existing for its exhibit in either of our repos?  This data should be hidden...

![image](https://cloud.githubusercontent.com/assets/7928978/8652542/30cf52dc-294d-11e5-913b-b04ed6a52750.png)

https://github.com/DC-OSSE/LearnDC_v2/tree/master/Export/JSON/lea/0143
https://github.com/socialdriver/learndc-data/tree/master/converted/lea/0143

**Comment by mepps** [comment]
@benjaminrobinson , we do have a file, from a previous commit I guess (it's in the new format clearly). Should I delete it and re-import? Were any other school's staff_degree files deleted since the exhibit was reformatted? (In the past I've only found where they were deleted before the reformatting).

**Comment by benjaminrobinson** [comment]
Ahh...yes.  Its the staff_degree file and not the hqt_classes file.  I included it in the OSSE .gitignore file so it should be removed and re-imported I guess...

https://github.com/DC-OSSE/LearnDC_v2/blob/master/.gitignore

**Comment by benjaminrobinson** [comment]
Not sure if there are any others like this but my first guess is to say no but check other files that were removed and added to our .gitignore file...

**Comment by mepps** [comment]
Is this correct in the gitignore:

Export/JSON/school/0168/staff_degree.json
Export/JSON/lea/0168/hqt_classes.json


that lea 0168 shouldn't have hqt classes and school 0168 shouldn't have staff_degree? Just wanted to make sure since they're the same code.

**Comment by benjaminrobinson** [comment]
Good catch!  Luckily I did not remove LEA code 0168's files...that should be school code 0168...I've update it in the .gitignore and will re-commit it now!  Thanks!

**Comment by benjaminrobinson** [comment]
LEA 0168 is Basis DC PCS, which should have a HQT Classes and Staff Degree exhibit...but school 0168 is The Next Step PCS, an adult/alternative high school, which should not have either of those!

**Comment by mepps** [comment]
Cool, will wait for another commit from you? I've removed the other files but will do a full import when all the data is ready.

**Comment by gwenrr** [comment]
May I ping on this again and ask for status? Thank you.

**Comment by mepps** [comment]
@gwenrr I thought I was waiting for a commit from @benjaminrobinson but unless either of the LEA 0168 files have changed, I can go ahead and do a new import and close this.

**Comment by mepps** [comment]
Doing the new import now, @benjaminrobinson let me know if there will be a new commit for that one file that was removed.

**Comment by mepps** [comment]
This is resolved in prod now.

**Comment by benjaminrobinson** [comment]
@mepps Thanks for getting this done!  So I never actually removed a file, I just accidentally included it in the .gitignore...I've made the commit changing the .gitignore back but just haven't made a push yet...
