### ISSUE TITLE
Graduation data - St. Coletta

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#157]
We need to hide graduation exhibit for St. Coletta (SC = 1047) (LEA code = 0143)

**Comment by benjaminrobinson** [comment]
Will close this thread and add this to #156 since its the same problem...

**Comment by gwenrr** [comment]
This is not the same as #156 - this is about ACGR not HQT so I am reopening

**Comment by benjaminrobinson** [comment]
It is a very similar problem...I removed St. Coletta's graduation and staff_degree files from the OSSE repo and added it to our .gitignore file...but the graduation file for St. Coletta is still showing in the Social Driver repo. @mepps.  Could you remove this file from the SD repo as well?

**Comment by mepps** [comment]
Removed files and importing now
