### ISSUE TITLE
Most recently pushed enrollment data

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#160]
Quick question: When you hit the "download" button from the staging site, the 2014 enrollment data is not there. Is that some special situation about the staging site that pushing to prod addresses, or is that something that needs to be addressed on staging? Thank you.

Gwen

**Comment by mepps** [comment]
@gwenrr @benjaminrobinson I can look into this this afternoon. Can you tell more about what's going on? Is this only LEAs or schools or both? My most recent data import on staging was just lea enrollment data and I don't think any other changes have been made between prod and staging.

**Comment by mepps** [comment]
Looking at staging just now, I'm seeing the 2014 data for school 0259 in the download. Let me know if you see something different.

**Comment by benjaminrobinson** [comment]
When Gwen and I were looking at this earlier today, it was just on the LEA profiles on the staging site...the fact that the visualization contains the 2014 enrollment audit data but the API call to the data download button does not contain that data.

**Comment by gwenrr** [comment]
from what I can see, this problem affects only LEAs (with the exception of the faux PCS sector report card on the LEA list). School and state report cards seem to include 2014 data when you hit the "download" button

**Comment by mepps** [comment]
@gwenrr That was a great catch! The issue was that the download wasn't pulling the latest code but the promoted code. (Luckily this means that production never had an issue). This is fixed in staging now.

**Comment by gwenrr** [comment]
Can we promote to prod now? Thanks.

**Comment by mepps** [comment]
@gwenrr That was done 10 minutes ago at @benjaminrobinson's  request :).

**Comment by benjaminrobinson** [comment]
:+1:
