### ISSUE TITLE
Loading problems (2) - Basis DC PCS - Attendance visualization

### ISSUE THREAD

**Issue by michaelaskew-sd** [DC-OSSE/LearnDC_v2#162]
Originally in #161. The visual is returning nothing at all. Seems to be specfic to this school, but should try and recreate locally and test around other schools.

Screenshot from http://www.learndc.org/schoolprofiles/view?s=0402#equityreport:

![image](https://cloud.githubusercontent.com/assets/9823840/9477961/181bd6ee-4b43-11e5-9aa9-7137fd60d99a.png)

**Comment by amberleyromo** [comment]
Reference: #161
