### ISSUE TITLE
Issue with file format

### ISSUE THREAD

**Issue by psteininger** [DC-OSSE/LearnDC_v2#165]
@benjaminrobinson I am working on implementing the compression into the workflow, but as a side effect I discovered an issue introduced into the existing data. most overview files for schools have a formatting issue. see these lines: https://github.com/DC-OSSE/LearnDC_v2/blame/master/Export/JSON/school/0099/overview.json#L32-L33
it should all be on 1 line, otherwise Ruby says JSON is malformed. I will add the accountability example. in another comment.

I will also fix the formatting locally, to continue, but the data will have to be regenerated without the format issue.

**Comment by psteininger** [comment]
@benjaminrobinson On second look, this may be an issue with something else

**Comment by psteininger** [comment]
it looks like I somehow was working off of an old version of the transfer code. sorry for the false alarm

**Comment by benjaminrobinson** [comment]
Hahah...No worries, @psteininger!  I know you're just doing your due diligence.  Thanks!
