### ISSUE TITLE
Front-end: Visibility on MYWE Labels

### ISSUE THREAD

**Issue by cmgiven** [DC-OSSE/LearnDC_v2#58]
In this school's Student Movement exhibit, the last two data labels of the withdrawal series are set to visibility: hidden. Can we look into what is causing that (proximity to the edge of the display?) and find a solution?

http://www.stage.learndc.org/schoolprofiles/view?s=0474#equityreport

**Comment by mepps** [comment]
Fixed. Extended the range for the graph.
