### ISSUE TITLE
Front-end: Print styles

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#59]

**Comment by cmgiven** [comment]
Issue was observed on IE11 under Windows 7.

**Comment by mepps** [comment]
Chris were you able to test on confirm that this happened independently? Do you know if it's all graphs or just the one in the screen shot?

**Comment by mepps** [comment]
Hi, so we discovered the issue here. By default, IE does not print background colors, which is how these graphs are set up. There is a setting users can turn on to print those colors. The least expensive solution is to set up a help text somewhere explaining that, either as an alert or a side panel. There are some possible fixes, but it is a known challenge and I worry about causing other issues to the site. I leave it to you and OSSE how best to approach this.

**Comment by cmgiven** [comment]
So explain how that alert would work?

Perhaps we add a print button at the top of the page that displays a modal with the message and upon dismissing uses Javascript to display the browser print dialog?

**Comment by mepps** [comment]
Hi Chris, I'm open to however you think it's best to display the information. I think a button that says "print" with a modal would be fine. Let me know if you'd like to discuss on the phone.

Also, I've figured out the issue with the tool-tip text not showing. I just have to work on a fix now.

**Comment by mepps** [comment]
Unhid the tooltip text.

**Comment by mepps** [comment]
Closing this because it is two issues, one of which is resolved.

**Comment by mepps** [comment]
See #81.
