### ISSUE TITLE
Data issue

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#60]
wanted to flag - Ben is investigating

![screenshot 2015-01-06 11 31 24](https://cloud.githubusercontent.com/assets/7264714/5631840/badc09b0-9597-11e4-86e3-2e92524f878b.png)

**Comment by gwenrr** [comment]
There is no reason a school should meet the minimum N threshold for two consecutive years of one-year MGP scores and not have a two-year score.

**Comment by benjaminrobinson** [comment]
This is a minimum n issue...

**Comment by benjaminrobinson** [comment]
I think the problem was that we were looking at math FAY sizes and this is MGP for reading.
