### ISSUE TITLE
Hide the DC Avg on Student Characteristics exhibit

### ISSUE THREAD

**Issue by cmgiven** [DC-OSSE/LearnDC_v2#61]
We need to hide all references to the DC average on the Student Characteristics exhibit, including where the data is shown in the charts as well as the legend. This should not affect any other Equity Report exhibit, and is limited to the Equity Report — the enrollment exhibit on LearnDC proper should continue to show in the same way.

The notion is that this functionality will be restored at some point in the future once consensus is reached on how the averages are calculated. But this will be after the Equity Report is launched.

**Comment by mepps** [comment]
Hi Chris, Let's check in about this tomorrow afternoon.

**Comment by mepps** [comment]
Are we getting better dc average data with the next push?

**Comment by cmgiven** [comment]
No, this will need to be removed at launch. May be restored at some point afterward.

**Comment by mepps** [comment]
I'm close to merging in a fix for this, but there is one issue I'm trying to resolve.

**Comment by mepps** [comment]
![screen shot 2015-01-14 at 12 57 17 pm](https://cloud.githubusercontent.com/assets/4406809/5744239/e6d66032-9bec-11e4-86dc-05604621eccb.png)

Change made on staging.

**Comment by gwenrr** [comment]
Since the DC average data is gone, can you please also hide the DC average in the legend? Thanks.

**Comment by gwenrr** [comment]
Can I flag that the DC average is now not showing on lots of exhibit? Like DC CAS, graduation, discipline and attendance? Or is this an artifact of you working on the staging site?

**Comment by mepps** [comment]
Both of these issues should be resolved as of now. Thanks for noticing this Gwen!
