### ISSUE TITLE
Front-end: Historical Data with <5 Years is Incorrectly Labeled

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#62]
When you click on Historical Data under subgroups.

![screenshot 2015-01-08 11 46 16](https://cloud.githubusercontent.com/assets/7264714/5666231/3e3e31a8-972c-11e4-923b-ef1f6820ac7f.png)

Labels read 2009 and 2010 - and this school (3068) was not open those years.

Similarly happening with SC = 1100, 0182, 3070

**Comment by cmgiven** [comment]
This school, 3068, only has two years of data, 2013 and 2014. Data appears correct. Labeling this as a front-end bug.

**Comment by mepps** [comment]
Looks like there is an assumption that all data starts in 2009. Will look into this.

**Comment by mepps** [comment]
![screen shot 2015-01-12 at 10 44 10 am](https://cloud.githubusercontent.com/assets/4406809/5705530/fca8d738-9a47-11e4-83e3-02b06709f453.png)

Fixed on staging.
