### ISSUE TITLE
DC CAS is missorted, identifies wrong all students data point for pull out

### ISSUE THREAD

**Issue by cmgiven** [DC-OSSE/LearnDC_v2#67]
On school code 0130, both math and reading.

**Comment by mepps** [comment]
I can resort the subgroups, but the data is displaying the correct subgroups and years. Can I get more specificity on what data is incorrect?

**Comment by cmgiven** [comment]
The pull out, the big number next to the description, appears to display whatever number is sorted first. So when all students is not first, it shows the wrong number.

**Comment by mepps** [comment]
![screen shot 2015-01-12 at 11 13 28 am](https://cloud.githubusercontent.com/assets/4406809/5706105/1787058a-9a4c-11e4-87ed-ed8717231fc7.png)

Sorted subgroups correctly.
