### ISSUE TITLE
Suppress Equity Reports for closed schools, STAYs, and CHOICE

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#69]
Booker T. Washington, SC = 0151
Community Academy PCS Amos III, 1109
Maya Angelou Evans Middle, 0133
Imagine SE, 1116
Choice, 0947
Roosevelt Stay, 0456
Ballou Stay, 0462

**Comment by cmgiven** [comment]
We need to create some sort of blacklist for these schools. Assigning to @mepps.

**Comment by mepps** [comment]
Is there any way this is indicated in the data?

**Comment by mepps** [comment]
Are the schools listed here all the schools that fit this criteria?

**Comment by benjaminrobinson** [comment]
Would this be something we add to the .gitignore file?

**Comment by cmgiven** [comment]
There is no way at the moment to add this to the data. We need the data to continue to appear for these schools, we just need to hide their Equity Report tab.

We could simply hardcode a blacklist of these school codes, at least for now, as it'll only ever need to be updated once a year.

**Comment by mepps** [comment]
Thanks for this list Gwen!

Booker T. Washington, SC = 0151
Community Academy PCS Amos III, 1109
Maya Angelou Evans Middle, 0133
Imagine SE, 1116
Choice, 0947
Roosevelt Stay, 0456
Ballou Stay, 0462
River Terrace - 304
Dunbar Pre Engineering – 940 (should not be separated from Dunbar; should be included in Dunbar’s)
IYP – 950
Luke C Moore – 884
Mamie D Lee – 265
Sharpe Health – 312
Washington Metropolitan – 474
Youth Services Center - 861

Also, this how the equity report tab looks for school 0304:

![screen shot 2015-01-15 at 9 25 52 am](https://cloud.githubusercontent.com/assets/4406809/5759022/90e1c19c-9c98-11e4-9eb6-bd964169b442.png)

Is that the way we want all equity reports hidden? I want to make sure I'm doing that correctly.

**Comment by cmgiven** [comment]
No, I think we actually want the tab itself hidden. Is that possible?

**Comment by gwenrr** [comment]
It looks like this school (River Terrace ES) closed several years ago. It should not have a page at all. It does not currently have a page on Learn DC (main site).

**Comment by mepps** [comment]
![screen shot 2015-01-15 at 3 00 52 pm](https://cloud.githubusercontent.com/assets/4406809/5765411/56899b9e-9cc7-11e4-8cfc-85a89560ed4e.png)

This is done. We can do this to all the schools on prod before launch as well.

**Comment by mepps** [comment]
Live on staging for the schools listed. Gwen, you're right about 0304, there's no report.

**Comment by cmgiven** [comment]
Confirming this closed.
