### ISSUE TITLE
Hide MYWE exhibit for SC = 0168 (the Next Step)

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#70]
Adult schools excluded from this metric

**Comment by cmgiven** [comment]
For clarity, the decision reached was that this data needs to remain on LearnDC, but we need to add a conditional rule to the Equity Report exhibit to hide for this specific school code.

**Comment by cmgiven** [comment]
This file will not be included in subsequent data pushes. The exhibit will be hidden everywhere. No longer a front-end issue, and closed.
