### ISSUE TITLE
Front-end: Specify 4-year for Graduation Rate pull out

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#74]
Not sure whether this is on your end or ours (it's like the issue we were having with shuffled values on DC CAS for DC Prep (SC = 0130).
![screenshot 2015-01-08 16 15 06](https://cloud.githubusercontent.com/assets/7264714/5670878/da5c2f2a-9751-11e4-9f41-3e8bb252bca5.png)

**Comment by cmgiven** [comment]
Note that you've switched the toggle to 5-year. The pull-out is the 4-year rate, so this is expected behavior.

**Comment by gwenrr** [comment]
Can we change the header, then, to say 4-Year Graduation rate, similar to what we did with MGP?

**Comment by gwenrr** [comment]
I didn't realize this - and only one LEA noticed. But I think it could be confusing.

**Comment by cmgiven** [comment]
@mepps: Let's change the label on the pull-label on this exhibit from "Graduation Rate" to "4-Year Graduation Rate".

**Comment by mepps** [comment]
![screen shot 2015-01-12 at 2 09 17 pm](https://cloud.githubusercontent.com/assets/4406809/5709082/a780c1ae-9a64-11e4-8358-41a71f0b5303.png)

Changed in staging. Thanks for an easy one! :)
