### ISSUE TITLE
Front-End: Student Growth should only pull 2013 and 2014

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#75]
Some of this is for us (Ben / underlying data) and some is for you.

Paul PCS Middle had test invalidations in 2014. So the MGP and DC CAS exhibits are looking weird.

For MGP - for the pull out number, the data are for 2013. So let's label as 2013 (similar to what we did for DC Scholars, SC = 3070, which only had one year, but for a different reason). 

For the subgroups, columns should read be labeled 2012-13 and 2013-2014. For the latter column, all should be n/a.

For DC average, the site is not showing 2014. It needs to pull from wherever that is, as do other schools.

**Comment by cmgiven** [comment]
http://www.stage.learndc.org/schoolprofiles/view?s=0170#equityreport

This school does not have 2014 MGP data. The front-end, however, is just selecting the two most recent years for which there is data (so in this case, 2012 and 2013). We need to change this to ensure that the exhibit only ever pulls 2013 and 2014 data. In this case, the missing 2014 data should be treated as an n/a.

**Comment by mepps** [comment]
Hmm, I could change it so it pulls for the maxYear from the state level. I don't want to hard code in 2014 since we may want to update next year without having to re-code.

**Comment by mepps** [comment]
This is the same as 79.
