### ISSUE TITLE
Paul PCS Middle School (SC = 0170) - DC CAS

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#76]
Following the previous issue, since Paul has 2014 DC CAS invalidations, the exhibit is basically blank.

We will figure out what to do next week.

**Comment by gwenrr** [comment]
PCSB and OSSE are fine with leaving this as is

So I am going to close.

![screenshot 2015-01-12 11 49 11](https://cloud.githubusercontent.com/assets/7264714/5706716/1986b8d0-9a51-11e4-8f08-5991aec9cba5.png)

**Comment by benjaminrobinson** [comment]
What does this mean for issue 75?
https://github.com/DC-OSSE/LearnDC_v2/issues/75

**Comment by gwenrr** [comment]
Issue #75 still needs to be dealt with.
