### ISSUE TITLE
Front-end: current year data missing

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#79]
It needs to pull from wherever that is, as do other schools.

**Comment by cmgiven** [comment]
Can you clarify?

**Comment by mepps** [comment]
This is from issue 75, trying to isolate out. This applies to Paul PCS Middle School (SC = 0170).

**Comment by mepps** [comment]
So I think it's not showing 2014 data because the code calculates the maxYear and shows that data. Either we have to show null for the school for 2014 or show 2013 data. We could have null for the main metric but show 2013 data everywhere else? What do others think?

**Comment by mepps** [comment]
Chris, can we discuss this as a larger issue tomorrow?

**Comment by gwenrr** [comment]
Paul Middle School has no 2014 DC CAS or 2014 MGP data because of invalidations. Which maybe is why it's also not pulling the state average data?

**Comment by mepps** [comment]
Will it have the data with the next push Gwen? Yes, that is why, it's looking for 2013 data. Thanks!

**Comment by gwenrr** [comment]
No it will not have 2014 data ever.

**Comment by mepps** [comment]
I'm still working on this. The problem is that I have to create a new array with null 2014 data. I should be able to finish this tomorrow morning.

**Comment by mepps** [comment]
We are working on the data import here, but is this in the only school that is missing the 2014 data? We will need to know this before the import.

**Comment by mepps** [comment]
I'm going to research this on our end for now.

**Comment by gwenrr** [comment]
I think so - but we can look into it.

**Comment by mepps** [comment]
I have a ruby script set to check the data, and we will add the missing school data (with null values) for the short term, assuming it's only one or two schools.

**Comment by cmgiven** [comment]
This is fine for the short term. In the long term, we could use the state data to identify the most recent year of testing, as there could be many cases in which it would not make sense to update the data with nulled values (closed schools, for example).

**Comment by mepps** [comment]
These are all the schools with missing 2014 data. Do we want to display null values for all of them?

0170
0188
0861
0947

**Comment by gwenrr** [comment]
For the second two (0861 and 0947): they should not have equity reports.

**Comment by gwenrr** [comment]
For 0170 (Paul) -  thought were would leave as is.

**Comment by gwenrr** [comment]
For 0188 (Cedar Tree) - hide the DC CAS and MGP exhibits, like with other early learning programs with no tested grades. Is that possible?

**Comment by mepps** [comment]
Hi Gwen, Can I get a list of all schools that shouldn't have equity reports displayed?

**Comment by mepps** [comment]
On 0170, my understanding was that we wanted the 2014 data to display for states and to display null values for 2014 for the school. Please let me know if that's incorrect.

**Comment by cmgiven** [comment]
Find the list of schools that should have their equity report hidden on issue #69.

On 0170, that's correct. My point is that we should be able to have the equity report identify that 2014 is missing without needing to insert a nulled 2014 into the data files. But as a short term solution, that's fine.

**Comment by gwenrr** [comment]
Booker T. Washington, SC = 0151
Community Academy PCS Amos III, 1109
Maya Angelou Evans Middle, 0133
Imagine SE, 1116
Choice, 0947
Roosevelt Stay, 0456
Ballou Stay, 0462
River Terrace - 304
Dunbar Pre Engineering – 940 (should not be separated from Dunbar; should be included in Dunbar’s)
IYP – 950
Luke C Moore – 884
Mamie D Lee – 265
Sharpe Health – 312
Washington Metropolitan – 474
Youth Services Center - 861

Some of these we have already identified. Some seem already not to have them.

**Comment by mepps** [comment]
Chris, can we discuss your thoughts on this issue before the final data push? Feel free to call me.

**Comment by mepps** [comment]
Chris, can you email me your phone number? I want to call you and discuss this in about 15. I think it's the last thing I have to deal with before import.

**Comment by mepps** [comment]
Hid student_growth and student_achievement for school 0170 only.

**Comment by cmgiven** [comment]
Confirming this closed.
