### ISSUE TITLE
Data: Paul PCS has old subgroup names

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#80]
http://learndc.localhost/schoolprofiles/view?s=0170#equityreport
From the data:
        "key": {
          "year": 2013,
          "subject": "math",
          "subgroup": "economy"
        },

This is an issue because it's comparing against the dc file and pulling the wrong averages.

**Comment by mepps** [comment]
Investigating futher first.

**Comment by mepps** [comment]
Wait I figured out the issue, dc data is missing mgp_2yr for 2013. Should we be supressing this for this school?

**Comment by mepps** [comment]
Duplicates 79

**Comment by gwenrr** [comment]
what is appearing on staging (DC CAS and MGP exhibits completely hidden) is not the solution I thought we were implementing.

I thought we were hiding DC CAS (or, more specifically, leaving it showing but without data).

For MGP, I thought we were going to have NA for 2014 but show 2013 (including making it clear that 2012-13 data were what was in pull out.

But I think we can leave as is for now and clean up later.

**Comment by cmgiven** [comment]
New issue #89
