### ISSUE TITLE
Front-end: Create help text because IE11 doesn't print background colors

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#81]
Hi, so we discovered the issue here. By default, IE does not print background colors, which is how these graphs are set up. There is a setting users can turn on to print those colors. The least expensive solution is to set up a help text somewhere explaining that, either as an alert or a side panel. There are some possible fixes, but it is a known challenge and I worry about causing other issues to the site. I leave it to you and OSSE how best to approach this.

**Comment by mepps** [comment]
Chris: So explain how that alert would work?

Perhaps we add a print button at the top of the page that displays a modal with the message and upon dismissing uses Javascript to display the browser print dialog?

**Comment by mepps** [comment]
Hi Chris, I'm open to however you think it's best to display the information. I think a button that says "print" with a modal would be fine. Let me know if you'd like to discuss on the phone.

Also, I've figured out the issue with the tool-tip text not showing. I just have to work on a fix now.

**Comment by cmgiven** [comment]
Yes, Maggie, I think that would work fine. Here's some text you can use for the modal:

In order for the charts on this page to be printed, please ensure that your browser's "Print background colors and images" option is turned on.

**Comment by mepps** [comment]
Should this go at the top or bottom of the page?

**Comment by cmgiven** [comment]
Top.

**Comment by mepps** [comment]
Sorry, just saw top of the page.

**Comment by cmgiven** [comment]
All good. And you might reference Casey's data download button designs for style ideas.

**Comment by mepps** [comment]
![screen shot 2015-01-15 at 2 10 57 pm](https://cloud.githubusercontent.com/assets/4406809/5764493/63eaf640-9cc0-11e4-8cd0-70267554ae4a.png)
![screen shot 2015-01-15 at 2 11 10 pm](https://cloud.githubusercontent.com/assets/4406809/5764494/63eb5ab8-9cc0-11e4-8bac-beb818826701.png)

Here's what I have right now.

**Comment by cmgiven** [comment]
Change the button to "PRINT THIS REPORT." Move it below the "What is an equity report?" heading.

Change the title of the modal to "Print This Report." Add a blue button to the lower right corner of the modal with the label "PRINT." Clicking that should open the print dialog.

That work?

**Comment by mepps** [comment]
![screen shot 2015-01-15 at 2 57 25 pm](https://cloud.githubusercontent.com/assets/4406809/5765347/dd344776-9cc6-11e4-8f2a-736c010547f6.png)

**Comment by mepps** [comment]
Print button goes into print dialog. Only question is whether the content should specify that this is for IE11?

**Comment by mepps** [comment]
(I also made sure the modal won't print. I could also do this for the button.)

**Comment by cmgiven** [comment]
(That'd be great.)

This works. Doesn't need to be limited to IE11. The language is taken from the IE11 print dialog, but since it's generally applicable, should be fine.

**Comment by mepps** [comment]
(done.) Live on staging now.

**Comment by cmgiven** [comment]
Clicking the "Print" button should also dismiss the modal. Otherwise, looks great.

**Comment by mepps** [comment]
I tried to incorporate this, but if you dismiss the  modal, the print dialog doesn't open. I can try to work on this as a qa fix though once everything else is settled.

**Comment by cmgiven** [comment]
All good. Closing.
