### ISSUE TITLE
Data: Need to incorporate updates to ACGR data

### ISSUE THREAD

**Issue by cmgiven** [DC-OSSE/LearnDC_v2#83]
@benjaminrobinson will be sharing an update soon once OSSE makes a determination about how they'd like to proceed given issues that have been identified with this data.

**Comment by benjaminrobinson** [comment]
I'm going to make a push tonight (it has updated prettified JSONs including the LEA enrollment JSON, which we were having an issue with earlier, and ONLY, I repeat, ONLY 4-year graduation rate data.  I was told by Jeff not to create the new data elements for 4 year graduation (so I'll get back to those tomorrow)...

**Comment by benjaminrobinson** [comment]
Imani and I are working to get the data together to set up the 5 year rates...According to our eyeball tests, the 4 year rates look to be around what we are expecting for the state level as well as for DCPS but more QA is probably needed before we feel 100% comfortable about those.  Back to work on the 5 year data for me!
