### ISSUE TITLE
DC CAS historical data ALL SCHOOLS

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#86]
Only data showing from my view of staging is 2014 for all students.

Buttons for subgroups don't work.

May be a Gwen issue (using Chrome) but can someone check?

**Comment by mepps** [comment]
I can see why this is happening and I will be able to fix it before launch.

**Comment by mepps** [comment]
![screen shot 2015-01-20 at 8 56 48 am](https://cloud.githubusercontent.com/assets/4406809/5818275/4ae57e8e-a082-11e4-8433-390ecd8b93d5.png)

Fixed on staging.
