### ISSUE TITLE
DC Average - ISA - Briya PCS 0126 - adult subgroup

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#87]
Can we hide DC average? It's showing 0%

**Comment by cmgiven** [comment]
Would it be better to instead add a DC value? @benjaminrobinson: did Tembo include a state adult-only value in their data file?

Would ideally prefer to minimize the number of exceptions like this that need to be added to the front-end.

**Comment by benjaminrobinson** [comment]
I will look into this...Thanks, Chris!

**Comment by benjaminrobinson** [comment]
After some investigation, I am unsure if we have a state adult-only value in the file since the State values (i.e. "AverageScore" in the files) are based on grade-bands...

**Comment by cmgiven** [comment]
Thanks, moving to @mepps plate. Maggie, can we catch when the state average is a null value and appropriately hide?

**Comment by mepps** [comment]
I tried to implement it but it's a bigger fix. I'm concerned that if I start changing more complex code before launch that we will cause other issues. Let's discuss at 10.

**Comment by gwenrr** [comment]
OK - but I think the ISA here should be 73% (which is the rate for Carlos Rosario, which is an adult school)

**Comment by gwenrr** [comment]
This is the all student rate for Carlos Rosario, which is all adults. Any reason that should not be the statewide ISA for the adult subgroup at Briya?

**Comment by gwenrr** [comment]
didn't mean to close

**Comment by benjaminrobinson** [comment]
Added 73% state average value.

**Comment by gwenrr** [comment]
Why is this exhibit now hidden / not showing for this school on prod? (Briya / SC = 0126)

![screenshot 2015-05-19 17 34 52](https://cloud.githubusercontent.com/assets/7264714/7714559/81454c24-fe4d-11e4-84dc-acf0dee47cdb.png)

**Comment by benjaminrobinson** [comment]
Its showing on staging...just an FYI!

**Comment by benjaminrobinson** [comment]
![image](https://cloud.githubusercontent.com/assets/7928978/7714630/01d845b2-fe4e-11e4-9503-170cd5dd8804.png)
