### ISSUE TITLE
Grade enrollment minimum N - still suppressing

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#88]
Need to fix logic. We are not suppressing for any minimum N for grade enrollment.

**Comment by cmgiven** [comment]
Do you have a school code for replication? Could not find an example.

**Comment by gwenrr** [comment]
I am not sure what you mean by this. The list of schools / grades affected is:

school_code	school_name		grade
292	OYSTER ADAMS BILINGUAL SCHOOL (OYSTER)		PK3
258	HEARST ES		PK3
305	ROSS ES		grade 5
173	ROOTS PCS		grade 5
173	ROOTS PCS		grade 6
173	ROOTS PCS		grade 7
173	ROOTS PCS		grade 8
947	CHOICE ACADEMY AT EMERY		UN
193	LATIN AMERICAN MONTESSORI BILINGUAL (LAMB) PCS		grade 5
131	HOPE COMMUNITY PCS LAMOND CAMPUS		grade 6
457	EASTERN HS		grade 12
126	BRIYA PUBLIC CHARTER SCHOOL		PK4
360	CAPITOL HILL MONTESSORI SCHOOL AT LOGAN		grade 5
360	CAPITOL HILL MONTESSORI SCHOOL AT LOGAN		grade 6
3066	SHINING STARS MONTESSORI PCS		grade 1
3066	SHINING STARS MONTESSORI PCS		grade 2
3066	SHINING STARS MONTESSORI PCS		KG
217	ACHIEVEMENT PREPARATORY PCS-ELEMENTARY		grade 4

Is this a coding issue on our end?

**Comment by cmgiven** [comment]
Yes, after spot checking a couple, it appears the front-end is working as expected. These values are missing from the data files. Assigning to Ben.

**Comment by benjaminrobinson** [comment]
This is for the Equity Report?  I thought we were still discussing having a minimum n....if not that is a matter of just re-running the ETL.

**Comment by benjaminrobinson** [comment]
Commented out enrollment suppression language from ETL file...and re-ran it.
