### ISSUE TITLE
Grades served language - content - MYWE

### ISSUE THREAD

**Issue by gwenrr** [DC-OSSE/LearnDC_v2#91]
Similar language to what's in ISA and discipline around grades served needs to be added to MYWE exhibit

**Comment by cmgiven** [comment]
Added.

**Comment by cmgiven** [comment]
@mepps: Flag that this was a content change in the staging environment. Let me know if I should make it elsewhere as well. Will confirm following launch.

**Comment by gwenrr** [comment]
It looks like this is fixed on staging but not on prod. Can someone look into this? Thanks.
