### ISSUE TITLE
Formatting: "null" to null

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#95]
Hey Ben, 

This isn't urgent, but in the most recent files (I think just attendance), the word null has quotes around it. I've had to change this with a find and replace since it will end up representing it differently. It would be better if it were changed in the etl file in the future. Thanks!

Maggie

**Comment by cmgiven** [comment]
I believe these only occur as placeholders for average daily attendance, a measure that we don't currently use anywhere on the site. Thanks for adding to the tracker. Let's move to the parking lot for now.

**Comment by benjaminrobinson** [comment]
Thanks for finding that, Maggie!  If Chris is right and that is the only place where this occurs, we can work something out but if not it probably has something to do with the ETL scripts themselves.  The jsonlite package in R has a function that allows for the treatment of missing values as either strings or as nulls and we choose to show them as nulls (and always have to my knowledge).  If limiting the JSON to not show average daily attendance in that ETL script can solve this issue, I would be down to do that down the line...

**Comment by benjaminrobinson** [comment]
Should I just remove the average daily attendance from the JSON completely, @cmgiven?

**Comment by cmgiven** [comment]
We can ask @mepps if that will cause API changes we'd prefer to avoid. I have no strong preferences here, but my sense is that these placeholders aren't harming anything, and if it's an easy fix to properly null them (probably by replacing a "null" string somewhere with an NA), that'd be the most straightforward option.

**Comment by mepps** [comment]
I don't think we're using average daily attendance, but I agree with Chris I think the best call is to null them, if the data is worth having there. Either shouldn't affect the front-end though.

**Comment by benjaminrobinson** [comment]
Great...can do!

**Comment by benjaminrobinson** [comment]
This should be changed with the next data commit/push...
