### ISSUE TITLE
Formatting: add Export/JSON/lea/4002/enrollment.json to .gitignore

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#96]
This can probably also go in the parking lot, but it causes an import error until I manually remove it.

**Comment by cmgiven** [comment]
This is DYRS. Currently just a nulled enrollment exhibit and a SPED APR exhibit. Ben, perhaps this entire LEA should be ignored?

**Comment by benjaminrobinson** [comment]
That would just entail adding their file to the .gitignore file, right?  Sure.

**Comment by cmgiven** [comment]
Yup, if you do it like this it will ignore the entire directory.

```Export/JSON/lea/4002```

Just remember to git rm it before making changes to the .gitignore.

**Comment by benjaminrobinson** [comment]
Can do!

**Comment by mepps** [comment]
Thanks, Ben! Also these files: 	converted/school/0104/mid_year_entry_and_withdrawal.json
	converted/school/0128/mid_year_entry_and_withdrawal.json
	converted/school/0137/mid_year_entry_and_withdrawal.json
	converted/school/0216/mid_year_entry_and_withdrawal.json
	converted/school/0456/mid_year_entry_and_withdrawal.json
	converted/school/0462/mid_year_entry_and_withdrawal.json
	converted/school/1119/mid_year_entry_and_withdrawal.json
My understanding is that that those schools shouldn't have mid-year entry and withdrawal exhibits?

**Comment by benjaminrobinson** [comment]
@mepps:  We want these files added to the .gitignore or we want them to be added to the gitrm command?  Just checking before I do any irreparable harm or something like that... :smile:

**Comment by cmgiven** [comment]
Two steps. We run git rm Export/json/school/0104/mid_year_entry_and_withdrawal.json ... to get rid of them. Make a commit along the lines of "deleted unwanted mid_year_entry_and_withdrawal exhibits." Poof, they're gone.

But if you were to now rerun the ETL, those files would be recreated, staged with the next git add -A, and committed with the next commit. So to prevent git from ever looking at those files again, we add them to your .gitignore and make a new commit along the lines of "ignore mid_year_entry_and_withdrawal exhibits for adult schools."

**Comment by benjaminrobinson** [comment]
Done and done...thank you, @cmgiven! :+1:
