### ISSUE TITLE
value to val in sped_apr

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#98]
Ben--thanks for looking into fiscal year, and being on top of it! That's a good point about whether year means the same. It would also be helpful if value was changed to val to be consistent with other data.

**Comment by benjaminrobinson** [comment]
Just making sure these issues are tied together...That is also something else I can do! #97

**Comment by mepps** [comment]
Awesome!

**Comment by benjaminrobinson** [comment]
Will be made in the next commit/push...
