### ISSUE TITLE
Sped APR: Data from 2012?

### ISSUE THREAD

**Issue by mepps** [DC-OSSE/LearnDC_v2#99]
This is just a question, but I'm noticing most of the sped_apr data is from 2012. Is this correct?

**Comment by benjaminrobinson** [comment]
FY 12-13 I believe, yes...I'm not 100% sure on the specifics so maybe @gwenrr can enlighten us!

**Comment by mepps** [comment]
@benjaminrobinson Good point about it being fiscal year!

**Comment by benjaminrobinson** [comment]
Maybe @cmgiven can help us out here as well...Is the LEA SPED APR data supposed to match the SPED APR data on the DC state profile?

http://www.learndc.org/schoolprofiles/view?s=dc#profile

**Comment by gwenrr** [comment]
Yes - this data is from FFY 2012 (7/1/2012-6/30/2013) specifically. The gap represents a reporting / analysis lag (I guess). The similar SPED APR data at the state level (on the state report card) is for this same year. (Not sure why this FFY is different from the traditional FFY, which runs from 10/1 to 9/30).
